version: "3"
services:
  spark:
    image: jupyter/sparkmagic-livy
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark
    ports:
      - "8998:8998"
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "true"
    links:
      - spark
    ports:
      - "8888:8888"
    user: root
    environment:
      NB_USER: 'james'
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
  jupyter_test:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "true"
    links:
      - spark
    ports:
      - "8891:8888"
    user: root
    environment:
      NB_USER: 'david'
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R